# Generated by Django 2.1.7 on 2020-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=64)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=64)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
        ),
    ]
