# Generated by Django 2.1.7 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='history',
            field=models.TextField(default='rider_history'),
        ),
    ]
